ログイン・ログアウト機能
shinonome-inc/backend-final-assignment-Yotaro pull request #2
Opened 2024-01-17 11:30 UTC by YotaroKono

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-01-24 22:04 UTC, yota33166 requested changes
最初の画面にログインボタンがないので、つけた方が良いと思います！
余裕があれば、
　ログイン中⇒ログアウトボタンを表示
　未ログイン⇒ログインボタン、サインアップボタンを表示
のように、ログイン状態によって表示を変えるとベターです。（チェック対象ではないのでお任せします！）

2024-01-24 22:04 UTC, yota33166 commented on templates/base.html
最初の画面にログインボタンがないので、つけた方が良いと思います！
余裕があれば、
　ログイン中⇒ログアウトボタンを表示
　未ログイン⇒ログインボタン、サインアップボタンを表示
のように、ログイン状態によって表示を変えるとベターです。（チェック対象ではないのでお任せします！）

2024-01-24 22:04 UTC, yota33166 commented on templates/registration/login.html
login.htmlは templates/accountsフォルダの中に入れておきましょう！
accounts/urls.pyで紐付けているhtmlファイルはtemplates/accountsフォルダにいれておくと分かりやすくなります（tweets/urls.py ⇒ templates/tweetsなども同様）

2024-01-25 15:12 UTC, YotaroKono commented on templates/registration/login.html
以下のエラーコードからlogin,htmlはregistrationフォルダーに置くように指定されていると解釈して、registrationフォルダに置いたのですが、それでも直した方が良いですか？


[
![Screenshot 2024-01-26 at 0 08 31](https://github.com/shinonome-inc/backend-final-assignment-Yotaro/assets/117880561/a104ef2f-07e8-40ad-b208-b723e56da9c7)
](url)

2024-01-25 16:30 UTC, YotaroKono commented on templates/base.html
ログインログアウト機能の修正_2で改善してみました！

2024-01-26 03:07 UTC, yota33166 commented on templates/registration/login.html
「デフォルトでregistrationフォルダーを参照している」という解釈は正しいです！
ただ今回は余分なフォルダを作りたくないので、login.htmlはaccountsフォルダ内に入れて、LoginViewのテンプレート参照先の方を変更しましょう！
（accounts/url.pyの中身を変えます）

2024-01-26 05:55 UTC, YotaroKono commented on templates/registration/login.html
承知しました！削除したので確認お願いします！

2024-01-26 07:03 UTC, yota33166 approved these changes

2024-01-27 03:29 UTC, YOSIJUKI reviewed
非常に良く書けていると思います！
以下の２点の修正をお願いします！

2024-01-27 03:29 UTC, YOSIJUKI commented on accounts/views.py
> +from mysite.settings import LOGIN_REDIRECT_URL
from mysite.settings import LOGIN_REDIRECT_URL
を
from django.conf import settings
に修正してください！
Djangoの設定システムをより効果的に利用することができます！

2024-01-27 03:29 UTC, YOSIJUKI commented on accounts/views.py
> +    success_url = reverse_lazy(LOGIN_REDIRECT_URL)
importの修正に伴いここも
LOGIN_REDIRECT_URLからsettings.LOGIN_REDIRECT_URLに変更してください！

2024-01-27 06:56 UTC, merged