ツイート機能
shinonome-inc/backend-final-assignment-Yotaro pull request #3
Opened 2024-02-01 11:41 UTC by YotaroKono

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-02-06 06:04 UTC, 4Franco-star commented on templates/tweets/detail.html
> +<a href="{% url 'tweets:delete' pk=tweet.id %}">削除</a>
ボタンを押しても他のユーザーが削除できないようにはなっていますが、それを試みることができてしまいます。if文を使ってツイートの所有主のみ削除できるようにしましょう！

2024-02-06 06:16 UTC, 4Franco-star commented on tweets/forms.py
フォームフィールドの定義は、views.pyの方で既に出来ているので、もしカスタマイズする予定がないのであれば、このファイルは削除しましょう。

2024-02-06 06:36 UTC, 4Franco-star commented on accounts/views.py
> +        context["tweets"] = Tweet.objects.all()
この実装では、全ユーザーのツイートを表示してしまっています。以下の順で実装して、プロフィールのユーザーに該当するツイートだけを表示させましょう！
・プロフィールページのURLからusernameというパラメータを取得
・そのパラメータに該当するユーザーを取得
・そのユーザーに該当するツイートをfilterを使って取得

2024-02-06 06:53 UTC, 4Franco-star commented on tweets/views.py
> +        context["tweets"] = Tweet.objects.all()
N+1問題が発生しています！
select_relatedを使ってください。

2024-02-06 06:56 UTC, 4Franco-star reviewed
ツイート機能お疲れ様でした！
大方よくできていると思います。4つコメントしましたので、修正お願いします！

2024-02-06 09:25 UTC, 4Franco-star commented on accounts/views.py
> +        context["tweets"] = Tweet.objects.filter(user=self.request.user)
request.userというのはログイン中のユーザーを指します。この状態だと、他のユーザーのプロフィールにも自分のツイートを表示させてしまいます。AユーザーのページにはAの、BユーザーのページにはBのツイートだけ、という風にする必要があります！Aユーザーのページにアクセスするとして、以下にコードと説明を記載します。

```
username = self.kwargs.get("username")
profile_user = get_object_or_404(User, username=username)
context["profile_user"] = profile_user
context["tweets"] = Tweet.objects.filter(user=profile_user)
```
まず、http://127.0.0.1:8000/accounts/A/からAというusernameを取り出します。
get_object_or_404()を使って、usernameフィールドにある名前と、取り出したusernameと一致するオブジェクトを取り出します。これでAというユーザーを取り出せ、profile_userに格納されます！
そして、userフィールドにあるユーザーと、profile_userと一致するツイートを取得すれば、Aユーザーのツイートだけを表示させることができます！
上記のコードを使ってください！

2024-02-06 09:30 UTC, 4Franco-star commented on templates/accounts/profile.html
> +<p>{{ user.username }}</p>
views.pyでの修正をもとにprofile_userにしてください！

2024-02-06 09:37 UTC, 4Franco-star commented on templates/tweets/home.html
> +    </li>
ログイン中のユーザーのプロフィールページに行くことはできますが、他人のはURLを打たないと入れないようです。
URLを追加しておきましょう！

2024-02-06 09:41 UTC, 4Franco-star reviewed
再修正が1点、新たな修正が2点コメントしました。
ご確認お願いします🙇

2024-02-06 12:54 UTC, YotaroKono commented on accounts/views.py
> +        context["tweets"] = Tweet.objects.filter(user=self.request.user)
承知しました！
ログインしているユーザーからフィルタリングしてツイート取得するのではなく、表示させているプロフィールページのユーザーからフィルタリングして、ツイートを取得するという認識であっていますかね...？

2024-02-06 14:38 UTC, 4Franco-star commented on accounts/views.py
> +        context["tweets"] = Tweet.objects.filter(user=self.request.user)
その認識で問題ありません！

2024-02-06 14:59 UTC, 4Franco-star commented on tweets/views.py
> +        profile_user = get_object_or_404(User, username=tweet.user.username)
[OK]
しっかりと理解されたようですね！
詳細ページのツイートを取得して、そのツイートのユーザー情報から名前を取得できています。
Tweetモデルのuserフィールドには外部キーが定義されているので、参照先のUserモデルのusernameを取得できます。

2024-02-06 15:00 UTC, 4Franco-star commented
一次LGTMです！

2024-02-07 04:05 UTC, masaya09 requested changes

2024-02-07 04:05 UTC, masaya09 commented on accounts/views.py
> +    context_object_name = "tweets"
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
TemplateViewにおいて、context_object_nameをクラス変数に記載しても意味ないです。

各クラスベースビューのクラス変数やメソッドは以下から簡単に確認できますので、ぜひ確認してください。
https://ccbv.co.uk/

2024-02-07 04:05 UTC, masaya09 commented on accounts/views.py
> +        return context
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
このViewでやりたいことは、ユーザーの表示と該当ユーザーのツイート一覧表示となります。
この点において言うと、もし該当ユーザーが100件以上ツイートしていた場合、毎回1つのページで全てのデータを取ってこようとします。

こう言うの避けるために、DjangoはListViewという汎用ビューを用意しています。これを用いると簡単にページネーションが実装できるようになります。

ぜひ、データが増えた時にも対応できるように実装してみてください。

2024-02-07 04:05 UTC, masaya09 commented on templates/tweets/detail.html
> +{% if user == tweets.user %}
![badge](https://img.shields.io/badge/review-suggestion-blue.svg) 
下記のようにしないと、削除ボタン表示されないはずです。実装・修正する際はきちんと runserver で画面確認して想定通りの実装できているかの確認は怠らないように気をつけましょう。

画面操作は本来統合テストでカバーするのですが、Djangoは統合テスト実装ができる環境にはなっていなく、実装するには3rd partyライブラリが必要なため、最終課題では単体テストしか求めてません。ですので、自分の作成したアプリが動作しているかは実装者がきちんと確認する必要があります。（現在のバックエンドアプリは基本的にAPI作成がメインなのでAPIは単体テストで賄えるため、そういった点でも統合テストを求めてないです。現在はフロントエンドでE2Eテストなどの統合テストをする方が主流です。ただ、DjangoやRailsといったフルスタックフレームワークはかつてこういった分野も通して一括テストをしてました。）

```suggestion
{% if user == tweet.user %}
```

2024-02-07 04:05 UTC, masaya09 commented on tweets/views.py
> +        profile_user = get_object_or_404(User, username=tweet.user.username)
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
N+1が起きてます。ここもdjango-debug-toolbarをインストールしていれば画面上で確認できますので、確認しながら直していってください。現状は以下のような状態になってしまってます。わからない場合はPGritで質問してください

<img width="1583" alt="スクリーンショット 2024-02-07 13 01 28" src="https://github.com/shinonome-inc/backend-final-assignment-Yotaro/assets/74097011/006cbc6e-8aa6-470c-af7d-4e7c4c361835">

2024-02-07 04:05 UTC, masaya09 commented on tweets/views.py
> +        context["tweets"] = Tweet.objects.select_related("user").all()
![must-badge](https://img.shields.io/badge/review-must-red.svg)
ここも UserDetailViewと同様に TemplateView においては context_object_name を記述しても意味ないです。

特にここは全てのユーザーのツイートが表示されるので ListViewを用いてページネーション対応しないと画面表示に時間がかかるようになってしまいます。

2024-02-07 09:56 UTC, masaya09 requested changes
コードフォーマッターのところでCIが結構な頻度で引っかかってしまってるようなので、pre_commitを用いて、コミットする前に自動で以下のコマンドが走るように対応してみても良さそうですね。

```bash
flake8
black .
isort .
```

2024-02-07 09:56 UTC, masaya09 commented on templates/tweets/delete.html
> +    <p>データ "{{ object }}" を本当に削除しますか?</p>
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
ここにおいて object という変数で対象のデータを表示できる理由を説明してみてほしいです。（その過程でもう一つの方で自動的にキー名が登録されていることに気づけるかと思いますので、そちらのキー名を用いた方が何のデータか分かりやすくなると思います。）

その上で、現状の状態だと以下のようなモデルクラスの入った表示で出てしまうので、Tweetモデルの__str__メソッドを定義して対応するか、フィールドにアクセスしてここで表示したいものを的確に表示するのが良いかと思います。

<img width="417" alt="スクリーンショット 2024-02-07 18 34 00" src="https://github.com/shinonome-inc/backend-final-assignment-Yotaro/assets/74097011/3d6839e2-afe2-47db-b3e1-a3d63a9c570b">

以下を確認して get_cotext_dataメソッドが中でどういった操作をやっているか確認してみてください。
https://ccbv.co.uk/projects/Django/5.0/django.views.generic.edit/DeleteView/#get_context_object_name

2024-02-07 09:56 UTC, masaya09 commented on tweets/views.py
> +        return Tweet.objects.select_related("user").all()
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
インスタンス変数にアクセスする必要がないときは、クエリセットはそのままクラス変数に定義できるので、そのように記述してください。わざわざget_querysetをオーバーライドする必要はないです。

2024-02-07 09:56 UTC, masaya09 commented on tweets/views.py
> +        context["profile_user"] = profile_user
![badge](https://img.shields.io/badge/review-suggestion-blue.svg)
以下で十分かと思います。

```suggestion
        context["profile_user"] = self.object.user
```

2024-02-07 09:56 UTC, masaya09 commented on tweets/views.py
> +        return super().get_queryset().select_related("user")
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも同様に、インスタンス変数を用いてないので、クエリセットはクラス変数に記述してしまいましょう。

2024-02-07 09:56 UTC, masaya09 commented on accounts/views.py
> +        return context
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
get_querysetのところGoodです。

ただ、profile_user のところで2度同じ処理をしてしまってます。特にこれはSQLが呼ばれるので対応すべきです。

ListViewの get_context_dataは以下のように記述されています。
https://ccbv.co.uk/projects/Django/5.0/django.views.generic.list/ListView/#get_context_data

ここから分かるようにget_context_dataメソッド内で`queryset = object_list if object_list is not None else self.object_list`というところがあります。この内、self.object_listは getメソッド内で呼ばれた get_querysetメソッドの返り値が入った値です。
https://ccbv.co.uk/projects/Django/5.0/django.views.generic.list/ListView/#get

つまり、get_context_dataメソッドを実行する段階で、すでにget_querysetメソッドは先に実行されているということがわかります。そうであれば、get_queryset内で呼び出した`profile_user = get_object_or_404(User, username=username)`をインスタンス変数化してしまえば、この変数をget_context_dataメソッド内でも呼べることができます。インスタンス変数にしてしまえば、アクセスできるので無駄なSQLを1つ減らせます。

インスタンス変数やクラス変数に関して分からない場合はぜひ調べてください。クラスビュー内で定義されているメソッドの実行順序がわかるようになるとどこでインスタンス変数化すると良いかなどがわかるので、ぜひそこも含めて以下サイトで各メソッドの処理を読んでみることをお勧めします。
https://ccbv.co.uk

2024-02-07 17:34 UTC, YotaroKono commented on templates/tweets/delete.html
> +    <p>データ "{{ object }}" を本当に削除しますか?</p>
デフォルトでdeleteviewではobjectにモデルのインスタンスが代入されて、それを呼び出すことでツイートの情報が表示されます。なのでobjectではtweetモデルの行名？インスタンス名？として「データ "Tweet object (5)" を本当に削除しますか?」が表示されているということですかね...
代わりに__str__メソッドを使ってモデルのカラムを指定してobjectに格納できるという認識で正しいですか？

2024-02-10 05:18 UTC, YotaroKono commented on accounts/views.py
> +        return context
わざわざget_context_data内で以下のような定義をしなくとも、
profile_user = get_object_or_404(User, username=username)
get_context_dataの、標準機能として以下が定義されているので、以下の(queryset)に変数として代入することで無駄なSQLを減らせるという認識で正しいですか？
context_object_name = self.get_context_object_name(queryset)

2024-02-10 10:14 UTC, masaya09 commented on templates/tweets/delete.html
> +    <p>データ "{{ object }}" を本当に削除しますか?</p>
> objectにモデルのインスタンスが代入

正確には、contextというdict型の変数に `object` というキーを追加し、そこにインスタンス（ここではツイートデータ）が代入されています。

該当箇所は [`get_context_data(self, **kwargs)`](https://ccbv.co.uk/projects/Django/5.0/django.views.generic.edit/DeleteView/#get_context_data)メソッドの SingleObjectMixin内で定義されている箇所です。

また、[`get_context_object_name`](https://ccbv.co.uk/projects/Django/5.0/django.views.generic.edit/DeleteView/#get_context_object_name)メソッド内で、実行されている以下の箇所の処理により、object という名前以外にも、`obj._meta.model_name` でも値を表示することができることを示しています。ですので、今回は object という名前で呼び出すよりも、 obj._meta.model_name ここでは、model = Tweet なので、tweet という変数で呼び出した方が良い、というのがここで求めていたことになります。

```python
elif isinstance(obj, models.Model):
    return obj._meta.model_name
```

2024-02-10 10:22 UTC, masaya09 requested changes

2024-02-10 10:22 UTC, masaya09 commented on templates/tweets/home.html
> +    {% for tweet in object_list %}
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
こちらも、DeleteViewのところで述べた通り、`object_list` で取ってこれますが、これが何のデータを意味してるのか分からないので、tweet_list で取ってくるか、context_object_nameクラス変数に、tweets と定義するなどして対応した方が良いですね。

2024-02-10 10:22 UTC, masaya09 commented on templates/accounts/profile.html
> +    {% for tweet in object_list %}
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
同様です

2024-02-10 10:22 UTC, masaya09 commented on accounts/views.py
> +        context["profile_user"] = self.profile_user
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
そうです。このようにインスタンス変数で定義すれば無駄なSQLを減らせます。

2024-02-10 10:22 UTC, masaya09 commented on tweets/models.py
> +        verbose_name_plural = "ツイート"
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
ここはなぜ、verbose_nameは定義せずにverbose_name_plural だけ定義しているのでしょうか？

2024-02-11 16:39 UTC, YotaroKono commented on tweets/models.py
> +        verbose_name_plural = "ツイート"
確認不足でした🙇

2024-02-12 07:25 UTC, masaya09 commented on tweets/views.py
> +        context["tweet"] = self.object
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
`context["tweet"] = self.object`の処理は`context = super().get_context_data(**kwargs)`で実行してるので不要です（deleteviewにて、htmlにtweetという値でデータが取ってこれるのと同じ理由です。今一度、get_context_dataの処理を把握しておいてください。この後のフォロー機能では個々の理解が必須となります。）

2024-02-12 17:37 UTC, YotaroKono commented on tweets/views.py
> +        context["tweet"] = self.object
ご解説ありがとうございます。なんで自動的このオブジェクト名が取得できるのかがイマイチ納得できずにここで記述したのですが、デフォルトで小文字にする処理がなされていると解説記事をみて納得しました！ありがとうございます🙇

2024-02-13 13:08 UTC, masaya09 approved these changes
![Yugi Thumb](https://media4.giphy.com/media/YOyi3Olf68kjbEB3g9/giphy.gif?cid=47028fa8evj8livyy00urckb2dmbs6227lgztkuyk07p6fbr&ep=v1_gifs&rid=giphy.gif&ct=g)

2024-02-13 13:08 UTC, merged